import type { Duplex } from 'node:stream';
import type Docker from 'dockerode';
import type { TerminalSize } from '@platform/shared';
import { AppError } from '../../errors/app-error.js';
import type { ExecutionHandle, TerminalOptions, TerminalSession } from '../provider.js';
import { createDemultiplexer } from './docker-process.js';

/**
 * A shell that belongs to the container, not to the connection watching it.
 *
 * ## The problem this solves
 *
 * The ordinary terminal is a Docker exec with a pseudo-terminal, and the control
 * plane holds its stream. There is no API for re-attaching to an exec, so when
 * the control plane restarts, the stream is gone and the shell is gone with it:
 * an install, a watch process or a long build is lost to a deploy of the
 * platform — the one moment nobody chose.
 *
 * ## How this one works
 *
 * The shell is started **detached, inside the container**, with plumbing that is
 * all just files:
 *
 * - a **named pipe** carrying what somebody types,
 * - a **log file** carrying everything the shell prints,
 * - `script`, which gives the shell a real pseudo-terminal and writes that log,
 * - and the pseudo-terminal's own path, written down so it can be resized.
 *
 * Nothing the control plane holds is load-bearing. Attaching is a *new* exec
 * that follows the log and copies keystrokes into the pipe; detaching ends that
 * exec and nothing else. The shell is a process in the container, and it is
 * still there after the platform restarts.
 *
 * ## Three things that were learned by running it
 *
 * These are here because the first version got each of them wrong, and each was
 * invisible until it ran against a real daemon:
 *
 * - **The attachment has no terminal of its own.** `script` already gives the
 *   shell one. A second, on the attachment, both double-processes keystrokes —
 *   holding them until Enter, which breaks arrow keys and Ctrl-C — and, with a
 *   named pipe on the other side, silently stops input arriving at all.
 * - **The pipe is opened read-write by the shell's side.** A reader that also
 *   holds the write end never sees end-of-input and never blocks waiting for a
 *   writer, so no helper process is needed to keep it open.
 * - **`script` is not in every image.** It is in the Debian-based language
 *   images and in the full BusyBox build; Alpine's cut-down BusyBox omits it.
 *   Starting is therefore checked, and a refusal is what makes the caller fall
 *   back to an ordinary terminal.
 */

/** Where a session's plumbing lives. One directory, so cleanup is one command. */
function paths(terminalId: string) {
  // Under /tmp, a bounded tmpfs: a runaway shell fills a ceiling rather than a
  // host disk. Named by the session, which the platform generated.
  const dir = `/tmp/.platform-terminals/${terminalId}`;
  return { dir, pipe: `${dir}/in`, log: `${dir}/out.log`, pid: `${dir}/pid`, tty: `${dir}/tty` };
}

/** Rejects anything that is not one of the platform's own identifiers. */
function assertTerminalId(terminalId: string): void {
  // These become shell words. They are generated by the platform and never
  // typed by anybody, so this is the second check rather than the first — and
  // it is the one standing between an identifier and a command substitution.
  if (!/^[a-zA-Z0-9-]{1,64}$/.test(terminalId)) {
    throw new AppError('EXECUTION_FAILED', 'A terminal could not be opened for this project.', {
      expose: true,
      context: { terminalId, problem: 'not a platform identifier' },
    });
  }
}

function sizeOf(size: TerminalSize): string {
  return `rows ${String(Math.max(1, Math.floor(size.rows)))} cols ${String(
    Math.max(1, Math.floor(size.columns)),
  )}`;
}

/** Starts the shell and leaves it running. */
export async function startDetachedTerminal(
  docker: Docker,
  handle: ExecutionHandle,
  terminalId: string,
  options: TerminalOptions & { user: string | null; home: string },
): Promise<void> {
  assertTerminalId(terminalId);

  const { dir, pipe, log, pid, tty } = paths(terminalId);
  const cwd = options.cwd ?? '.';

  /*
   * The inner command records which pseudo-terminal it was given before it
   * becomes the shell, so a resize can reach that terminal directly instead of
   * being typed into somebody's prompt.
   */
  const inner = `tty > '${tty}'; stty ${sizeOf(options.size)} 2>/dev/null; exec /bin/sh -i`;

  const script = [
    `command -v script >/dev/null 2>&1 || { echo missing-script; exit 0; }`,
    `mkdir -p '${dir}'`,
    `rm -f '${pipe}' '${log}' '${pid}' '${tty}'`,
    `mkfifo '${pipe}'`,
    `: > '${log}'`,
    `cd '${cwd}' 2>/dev/null || true`,
    // `<>` opens the pipe read-write: never blocks, never reads end-of-input.
    `setsid script -q -f -c "${inner}" '${log}' <>'${pipe}' >/dev/null 2>&1 & echo $! > '${pid}'`,
    `sleep 1`,
    `kill -0 "$(cat '${pid}')" 2>/dev/null && echo started || echo failed`,
  ].join('\n');

  const output = await runToCompletion(docker, handle, script, options.user, {
    TERM: 'xterm-256color',
    HOME: options.home,
  });

  if (!output.includes('started')) {
    throw new AppError(
      'EXECUTION_FAILED',
      'A terminal that survives a restart could not be started in this environment.',
      {
        expose: true,
        context: {
          terminalId,
          reason: output.includes('missing-script') ? 'no script in image' : 'did not start',
        },
      },
    );
  }
}

/**
 * Attaches to a shell that is already running.
 *
 * `tail` follows the last stretch of the log, so whoever attaches sees the
 * screen they left; `cat` copies keystrokes into the pipe, one byte at a time
 * as they arrive, because there is no terminal here to hold them until Enter.
 *
 * Bounded in **bytes** rather than lines: a terminal log is raw pseudo-terminal
 * output full of escape sequences, and counting lines would cut a redraw in
 * half.
 */
export async function attachDetachedTerminal(
  docker: Docker,
  handle: ExecutionHandle,
  terminalId: string,
  identity: { user: string | null; home: string; replayBytes: number },
): Promise<TerminalSession> {
  assertTerminalId(terminalId);

  const { pipe, log, tty } = paths(terminalId);
  const container = docker.getContainer(handle.externalId);

  let exec: Docker.Exec;
  let stream: Duplex;

  try {
    exec = await container.exec({
      Cmd: [
        '/bin/sh',
        '-c',
        `tail -c ${String(identity.replayBytes)} -f '${log}' & exec cat >> '${pipe}'`,
      ],
      ...(identity.user ? { User: identity.user } : {}),
      Env: [`HOME=${identity.home}`],
      AttachStdin: true,
      AttachStdout: true,
      AttachStderr: true,
      // Deliberately no terminal. See the notes at the top of this file.
      Tty: false,
    });

    stream = (await exec.start({ hijack: true, stdin: true })) as unknown as Duplex;
  } catch (error) {
    throw new AppError('EXECUTION_FAILED', 'That terminal could not be reattached.', {
      expose: true,
      cause: error,
      context: { containerId: handle.externalId, terminalId },
    });
  }

  let closed = false;
  const listeners: ((chunk: Uint8Array) => void)[] = [];
  const exits: ((code: number | null) => void)[] = [];

  /*
   * Output that arrives before anybody is listening is held, not dropped.
   *
   * The replay starts the instant this connects, and the caller subscribes a
   * moment later — after writing the session's row. The prompt lands in that
   * gap, and an idle shell prints nothing more, so dropping it left a blank
   * terminal. Found by the browser suite, not by reading the code.
   */
  const early: Uint8Array[] = [];

  // Without a terminal Docker frames the output; this takes the frames apart so
  // the browser receives the shell's own bytes and nothing else.
  const demultiplex = createDemultiplexer(({ chunk }) => {
    if (listeners.length === 0) {
      early.push(chunk);
      return;
    }
    for (const listener of listeners) listener(chunk);
  });
  stream.on('data', (chunk: Buffer) => demultiplex(chunk));

  const finish = (): void => {
    if (closed) return;
    closed = true;
    // Null, not zero. Detaching says nothing about how the shell ended, and it
    // very probably has not: that is the whole point of this file.
    for (const listener of exits) listener(null);
  };

  stream.on('end', finish);
  stream.on('close', finish);
  stream.on('error', finish);

  return {
    onData(listener) {
      listeners.push(listener);
      if (listeners.length === 1) {
        for (const chunk of early.splice(0)) listener(chunk);
      }
    },
    onExit(listener) {
      exits.push(listener);
    },
    write(data) {
      if (!closed) stream.write(data);
    },
    async resize(size) {
      /*
       * Set on the shell's own pseudo-terminal, from the side.
       *
       * Changing a terminal's size makes the kernel tell whatever is in the
       * foreground, so a full-screen program redraws itself. Nothing is typed
       * into the shell, which is what an earlier version did and which put a
       * `stty` command on somebody's screen every time they resized a window.
       */
      await runToCompletion(
        docker,
        handle,
        `stty -F "$(cat '${tty}')" ${sizeOf(size)} 2>/dev/null || true`,
        identity.user,
        {},
      ).catch(() => undefined);
    },
    async close() {
      /*
       * Ends the attachment and leaves the shell alone.
       *
       * The distinction this whole file is about: closing the window is not
       * closing the session, so nothing here signals the shell.
       */
      closed = true;
      stream.end();
      stream.destroy();
      await Promise.resolve();
    },
  };
}

/** Ends the shell and removes its plumbing. Called when a session is closed. */
export async function stopDetachedTerminal(
  docker: Docker,
  handle: ExecutionHandle,
  terminalId: string,
  user: string | null,
): Promise<void> {
  assertTerminalId(terminalId);

  const { dir, pid } = paths(terminalId);

  /*
   * `script` is signalled, and the shell goes with it.
   *
   * The shell is in a session of its own that `script` created, so a group
   * signal to `script` does not reach it directly — but ending `script` closes
   * the terminal's other side, and the kernel hangs up everything on it, which
   * is exactly "close this terminal and what is running in it".
   */
  const script = [
    `if [ -f '${pid}' ]; then kill -TERM "$(cat '${pid}')" 2>/dev/null || true; fi`,
    `sleep 1`,
    `if [ -f '${pid}' ]; then kill -KILL "$(cat '${pid}')" 2>/dev/null || true; fi`,
    `rm -rf '${dir}'`,
  ].join('\n');

  await runToCompletion(docker, handle, script, user, {}).catch(() => undefined);
}

/** Whether the shell for a session is still running inside the container. */
export async function detachedTerminalRunning(
  docker: Docker,
  handle: ExecutionHandle,
  terminalId: string,
  user: string | null,
): Promise<boolean> {
  assertTerminalId(terminalId);

  const { pid } = paths(terminalId);
  const output = await runToCompletion(
    docker,
    handle,
    `if [ -f '${pid}' ] && kill -0 "$(cat '${pid}')" 2>/dev/null; then echo yes; else echo no; fi`,
    user,
    {},
  ).catch(() => 'no');

  return output.includes('yes');
}

/** Runs a short command and returns everything it printed. */
async function runToCompletion(
  docker: Docker,
  handle: ExecutionHandle,
  script: string,
  user: string | null,
  env: Record<string, string>,
): Promise<string> {
  const exec = await docker.getContainer(handle.externalId).exec({
    Cmd: ['/bin/sh', '-c', script],
    ...(user ? { User: user } : {}),
    Env: Object.entries(env).map(([key, value]) => `${key}=${value}`),
    AttachStdout: true,
    AttachStderr: true,
    Tty: false,
  });

  const stream = (await exec.start({ hijack: true, stdin: false })) as unknown as Duplex;

  return new Promise<string>((resolve) => {
    let text = '';
    const demultiplex = createDemultiplexer(({ chunk }) => {
      text += Buffer.from(chunk).toString('utf8');
    });
    stream.on('data', (chunk: Buffer) => demultiplex(chunk));
    stream.on('end', () => resolve(text));
    stream.on('close', () => resolve(text));
    stream.on('error', () => resolve(text));
  });
}
